#!/bin/sh

PID_FILE=/tmp/sshuttle.pid

connect() {
    sshuttle --dns -vr <username>@lxplus.cern.ch 128.141.0.0/16 128.142.0.0/16 137.138.0.0/16 185.249.56.0/22 188.184.0.0/15 192.65.196.0/23 192.91.242.0/24 194.12.128.0/18 2001:1458::/32 2001:1459::/32 --daemon --pidfile $PID_FILE
}

disconnect() {
    kill `cat $PID_FILE`
}

case $1 in
    connect|c)
        connect
        shift
    ;;
    disconnect|d)
        disconnect
        shift
    ;;
    *)
        if [ -f "$PID_FILE" ]; then
            echo "disconnecting..."
            disconnect
        else
            echo "connecting..."
            connect
        fi
   ;;
esac
